name: C/C++ CI

on:
  [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make ./exercise4/
    - name: test
      run: exercise4/test/main.cpp
